using System.Collections.Generic;

namespace Navmesh;

internal static class Loc
{
    private static readonly Dictionary<string, string> Map = new()
    {
        ["Automatically load/build navigation data when changing zones"] = "切換區域時自動載入/建立導航資料",
        ["Enable DTR bar"] = "啟用伺服器資訊列顯示",
        ["Show detailed query status in DTR"] = "在伺服器資訊列顯示詳細查詢狀態",
        ["Align camera to movement direction"] = "鏡頭自動對齊移動方向",
        ["Camera height (degrees)"] = "鏡頭高度（度）",
        ["Show active waypoints"] = "顯示目前路徑點",
        ["Always visualize game collision"] = "永遠顯示遊戲碰撞資料",
        ["Cancel current path on player movement input"] = "玩家手動移動時取消目前路徑",
        ["Stop pathing when stuck"] = "卡住時停止移動",
        ["Max cores used during mesh build"] = "建立導航網格時使用的最大核心數",
        ["0 = use all available; positive number = use that many cores; negative number = leave that many cores idle"] = "0 = 使用全部可用核心；正數 = 使用該數量的核心；負數 = 保留該數量的核心不使用",
        ["Stuck tolerance (yalms/second)"] = "卡住容許值（碼/秒）",
        ["The minimum distance the object must move each frame to avoid being considered stuck."] = "物件每禎必須移動的最小距離，低於此值將視為卡住。",
        ["Stuck timeout (ms)"] = "卡住逾時時間（毫秒）",
        ["How long you can remain under the stuck threshold before stopping."] = "低於卡住門檻值多久後才會停止移動。",
        ["Retry pathing after stop"] = "停止後重新嘗試尋路",
        ["If enabled, the agent will attempt to re-path after being considered stuck."] = "啟用後，判定卡住時將會嘗試重新規劃路徑。",
        ["Randomness Multiplier"] = "隨機性倍率",

        ["Rasterization: Cell Size (#cs)"] = "光柵化：格子大小 (#cs)",
        ["Rasterization: Cell Height (#ch)"] = "光柵化：格子高度 (#ch)",
        ["Agent: Height"] = "角色：高度",
        ["Agent: Radius"] = "角色：半徑",
        ["Agent: Max Climb"] = "角色：最大攀爬高度",
        ["Agent: Max Slope"] = "角色：最大坡度",
        ["Filtering"] = "過濾設定",
        ["Region: Min Size"] = "區域：最小面積",
        ["Region: Merge Size"] = "區域：合併面積",
        ["Partitioning algorithm"] = "分割演算法",
        ["Polygonization: Max Edge Length"] = "多邊形化：最大邊長",
        ["Polygonization: Max Edge Simplification Error"] = "多邊形化：最大邊緣簡化誤差",
        ["Polygonization: Max Vertices per Polygon"] = "多邊形化：每個多邊形最大頂點數",
        ["Detail Mesh: Sample Distance"] = "細節網格：取樣距離",
        ["Detail Mesh: Max Sample Error"] = "細節網格：最大取樣誤差",
        ["L1 Tile count"] = "L1 圖塊數量",
        ["L2 Tile count"] = "L2 圖塊數量",
        ["L3 Voxel count"] = "L3 體素數量",
        ["Generate climb-down links"] = "產生向下攀爬連結",
        ["Generate jump-down links"] = "產生向下跳躍連結",
        ["Ground tolerance"] = "地面容許值",
        ["Undocumented"] = "尚無說明文件",
        ["Climb down distance"] = "向下攀爬距離",
        ["Climb down max height"] = "向下攀爬最大高度",
        ["Climb down min height"] = "向下攀爬最小高度",
        ["Edge jump end distance"] = "邊緣跳躍終點距離",
        ["Edge jump height"] = "邊緣跳躍高度",
        ["Edge jump max drop"] = "邊緣跳躍最大落差",
        ["Edge jump min drop"] = "邊緣跳躍最小落差",
        ["Low-hanging obstacles"] = "低矮障礙物",
        ["Ledge spans"] = "邊緣區塊",
        ["Walkable low-height spans"] = "可通行的低矮區塊",
        ["Interiors"] = "室內區域",

        ["Log raycasts"] = "記錄射線檢測",
        ["Reset remembered raycast hit"] = "重置已記錄的射線命中",
        ["Show objects with zero layer"] = "顯示零層級物件",
        ["Hide objects without raycast flag (0x1)"] = "隱藏沒有射線檢測旗標的物件 (0x1)",
        ["Hide objects without global viist flag (0x2)"] = "隱藏沒有全域造訪旗標的物件 (0x2)",
        ["Copy translation to clipboard"] = "複製座標至剪貼簿",
        ["Flag: raycast"] = "旗標：射線檢測",
        ["Flag: global visit"] = "旗標：全域造訪",
        ["Export to DotRecast obj file"] = "匯出為 DotRecast obj 檔案",
        ["Group by layer group"] = "依圖層群組分組",
        ["Group by layer"] = "依圖層分組",
        ["Group by instance type"] = "依實例類型分組",
        ["Group by material"] = "依材質分組",
        ["Reload"] = "重新載入",
        ["Rebuild"] = "重建",
        ["Set target to current pos"] = "將目標設為目前座標",
        ["Set target to target pos"] = "將目標設為目標座標",
        ["Set target to flag position"] = "將目標設為旗標位置",
        ["Export bitmap"] = "匯出點陣圖",
        ["Allow movement"] = "允許移動",
        ["Use raycasts"] = "使用射線檢測",
        ["Use string pulling"] = "使用拉線演算法",
        ["Pathfind to target using navmesh"] = "使用導航網格尋路至目標",
        ["Pathfind to target using volume"] = "使用體積尋路至目標",
        ["Support flying"] = "支援飛行",
        ["Load existing territory customization"] = "載入現有的區域自訂設定",
        ["Rebuild navmesh"] = "重建導航網格",
        ["Rebuild scene extract only"] = "僅重建場景擷取",
        ["Pathfind"] = "尋路",
    };

    public static string T(string s) => Map.TryGetValue(s, out var v) ? v : s;
}
