name: Build Check

on:
  push:
    branches:
      - 'tc-7.20'
    tags-ignore:
      - "v*"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud (TC pin)
        run: |
          wget https://github.com/zodiac0806/BossmodReborn-TC/releases/download/dalamud-pin-v13.0.0.16/dalamud-api13-net9.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }} || [ $? -eq 1 ]
          test -f ${{ env.DALAMUD_HOME }}/Dalamud.dll

      - name: Restore Project
        run: dotnet restore vnavmesh/vnavmesh.csproj

      - name: Build Project
        run: dotnet build --configuration Release vnavmesh/vnavmesh.csproj
